#!/usr/bin/env node

const MidiEngine = require('./midiEngine')
var MidiWriter = require('midi-writer-js')
const fs = require('fs')
const tmp = require('tmp')

var program = require('commander')

/*
let author = 'qub1t'
let numPatchesToGenerate = 64;
let bankPath = '/Users/priebe/Library/Audio/Presets/Helm/helmgen';
let folder = 'helmgen';
let patchBase = 'helmgen';
let perturbFactor = 0.1;
*/

program
  .version('0.0.1', '-v, --version')
  .option('-s, --swing-interval <swing-interval>', 'swing interval, either 8 or 16')
  .option('-S, --swing-percentage <swing-percentage>', 'swing percentage, 25 to 75')
  .option('-o, --output <filename>', 'MIDI file to write the beats to')
  .option('-p, --preview', 'preview MIDI')
  .option('-m, --midi-port <port num>', 'MIDI port num')
  .option('-t, --tempo', 'tempo (in bpm) for preview, defaults to 127')
  .option('-l, --list-midi-ports', 'list MIDI ports')
  .parse(process.argv)

if (program.listMidiPorts) {
  let me = new MidiEngine()
  me.listMidiPorts()
  process.exit(0)
}
if (!program.output) {
  console.error('No output file specified.  Exiting.')
  process.exit(1)
}
if (program.swingInterval === 8) {
  program.swingInterval = 64
} else {
  program.swingInterval = 32
}
if (!program.swingPercentage) {
  program.swingPercentage = 50
}
if (!program.tempo) {
  program.tempo = 127
}

if (program.preview && (typeof program.midiPort === 'undefined')) {
  console.error('Must specify a MIDI port number when using the -p option.')
  process.exit(1)
}

var PatternGenerator = require('./patternGenerator')

const Configstore = require('configstore')
const pkg = require('./package.json')
const conf = new Configstore(pkg.name, {})

var HbgKit = require('./hbgKit')
var kit = new HbgKit()

let drumMap = conf.get('drumMap')
if (drumMap) {
  kit.setDrumMap(drumMap)
  kit.selectRandomDrums()
}

let me = new MidiEngine()

let gen = new PatternGenerator(kit)
gen.selectPatterns()

if (!program.preview) {
  writeFullTrack()
  process.exit(0)
}

function writeFullTrack () {
  gen.setSwing(16, 50)
  let track = gen.generate(null, 16)

  let w = new MidiWriter.Writer([track])
  let buffer = Buffer.from(w.buildFile())
  fs.writeFileSync(program.output, buffer, function (err) {
    if (err) return console.log(err)
  })
}

var _previewFile = ''
buildUI()

function onUiCallback (e) {
  switch (e.action) {
    case 'new-sound':
      kit.selectRandomDrum(e.val)
      generatePreviewTrack()
      startPreview()
      break
    case 'new-pattern':
      console.log('selecting new pattern for ' + e.val)
      gen.selectPattern(e.val)
      generatePreviewTrack()
      startPreview()
      break
    case 'play':
      startPreview()
      break
    case 'reset':
      kit.selectRandomDrums()
      gen.selectPatterns()
      generatePreviewTrack()
      startPreview()
      break
    case 'save':
      writeFullTrack()
      break
  }
}

function startPreview () {
  me.stop()
  me.playFile(_previewFile, program.tempo)
}

function generatePreviewTrack () {
  gen.setSwing(program.swingInterval, program.swingPercentage)

  let track = gen.generate(['hardtrack2'], 8)
  let w = new MidiWriter.Writer([track])
  let buffer = Buffer.from(w.buildFile())
  let tmpobj = tmp.fileSync()
  _previewFile = tmpobj.name
  fs.writeFileSync(_previewFile, buffer, function (err) {
    if (err) return console.log(err)
  })
}

function buildUI () {
  me.openPort(program.midiPort)

  generatePreviewTrack()

  let drums = kit.getDrums()
  let xary = []
  for (let d in drums) {
    xary.push(d)
  }
  drums = xary

  let components = gen.getPatternIdentifiers()

  let ui = require('./ui')
  let u = new ui(components, drums, onUiCallback)
  u.create()
}
